SET FOREIGN_KEY_CHECKS = 0;
/*LIO RAFFO (EPFL/CEMI)
--Gianluca Tarasconi*/
drop table if exists tls201_appln;
drop table if exists tls202_appl_title;
drop table if exists tls203_appln_abstr;
drop table if exists tls204_appln_prior;
drop table if exists tls205_tech_rel;
drop table if exists tls206_person;
drop table if exists tls207_pers_appln;
drop table if exists tls208_doc_std_nms;
drop table if exists tls209_appln_ipc;
drop table if exists tls210_appln_n_cls;
drop table if exists tls211_pat_publn;
drop table if exists tls212_citation;
drop table if exists tls214_npl_publn;
drop table if exists tls215_citn_categ;
drop table if exists tls216_appln_contn;
/*drop table if exists tls217_appln_ecla;*/
drop table if exists tls218_docdb_fam;
drop table if exists tls219_inpadoc_fam;
drop table if exists tls222_appln_jp_class;
drop table if exists tls223_appln_docus;
drop table if exists TLS224_APPLN_CPC;
drop table if exists TLS226_PERSON_ORIG;
SET FOREIGN_KEY_CHECKS = 1;


CREATE TABLE tls201_appln
	(
		APPLN_ID					INT(11) NOT NULL default '0',
		APPLN_AUTH					CHAR(2) NOT NULL default '',
		APPLN_NR					VARCHAR(15) NOT NULL default '',
		APPLN_KIND					CHAR(2) NOT NULL default '00',
		APPLN_FILING_DATE			DATE NOT NULL default '9999-12-31',
		IPR_TYPE					CHAR(2) NOT NULL default '',
		APPLN_TITLE_LG				CHAR(2) NOT NULL default '',
		APPLN_ABSTRACT_LG			CHAR(2) NOT NULL default '',
		INTERNAT_APPLN_ID			INT(11) NOT NULL default '0',
		APPLN_FILING_YEAR_MONTH		MEDIUMINT(9),
		APPLN_FILING_YEAR			SMALLINT(6),
		PRIOR_EARLIEST_DATE			DATE,
		PRIOR_EARLIEST_YEAR_MONTH	MEDIUMINT(9),
		PRIOR_EARLIEST_YEAR			SMALLINT(6),
		PUBLN_EARLIEST_DATE			DATE,
		PUBLN_EARLIEST_YEAR_MONTH	MEDIUMINT(9),
		PUBLN_EARLIEST_YEAR			SMALLINT(6),
		PUBLN_EARLIEST_REF			VARCHAR(30),
		EARLIEST_PAT_PUBLN_ID		INT(11),
		NB_APPLICANTS				SMALLINT(6),
		NB_INVENTORS				SMALLINT(6),
		NB_CITATIONS				SMALLINT(6),
		GRANTED						TINYINT(4),
		DOCDB_FAMILY_ID				INT(11),
		DOCDB_FAMILY_SIZE 			SMALLINT(6),
		PRIMARY KEY (APPLN_ID)
	)
	ENGINE=INNODB CHARACTER SET utf8;
	
CREATE TABLE tls202_appl_title
	(
		APPLN_ID 			INT(11) NOT NULL,
		APPLN_TITLE       	VARCHAR(5000) NOT NULL,
		PRIMARY KEY (APPLN_ID),
		FOREIGN KEY (APPLN_ID) REFERENCES tls201_appln(appln_id)
	)
		ENGINE=INNODB CHARACTER SET utf8;
	
CREATE TABLE tls203_appln_abstr
	(
		APPLN_ID 			INT(11) NOT NULL,
		APPLN_ABSTRACT  	VARCHAR(12000) NOT NULL,
		PRIMARY KEY (APPLN_ID),
		FOREIGN KEY (APPLN_ID) REFERENCES tls201_appln(appln_id)
	)
	ENGINE=INNODB CHARACTER SET utf8;

CREATE TABLE tls204_appln_prior
	(
		APPLN_ID 			int(11) NOT NULL,
		PRIOR_APPLN_ID 		int(11) NOT NULL,
		PRIOR_APPLN_SEQ_NR 	smallint(6) default NULL,
		PRIMARY KEY  (APPLN_ID,PRIOR_APPLN_ID),
		FOREIGN KEY  (APPLN_ID)  		REFERENCES TLS201_APPLN(APPLN_ID),
		FOREIGN KEY  (PRIOR_APPLN_ID)  	REFERENCES TLS201_APPLN(APPLN_ID)
	)
		ENGINE=INNODB CHARACTER SET utf8;
CREATE TABLE tls205_tech_rel
	(
		APPLN_ID  			int(11) NOT NULL,
		TECH_REL_APPLN_ID 	int(11) NOT NULL,
		PRIMARY KEY  (APPLN_ID, TECH_REL_APPLN_ID),
		FOREIGN KEY  (APPLN_ID)  			REFERENCES TLS201_APPLN(APPLN_ID),
		FOREIGN KEY  (TECH_REL_APPLN_ID)  	REFERENCES TLS201_APPLN(APPLN_ID)
	)
		ENGINE=INNODB CHARACTER SET utf8;

CREATE TABLE tls208_doc_std_nms
	(
		DOC_STD_NAME_ID 	int(11) NOT NULL default '0',
		DOC_STD_NAME       	VARCHAR(150) NOT NULL default '',
		PRIMARY KEY  (DOC_STD_NAME_ID)
	)
		ENGINE=INNODB CHARACTER SET utf8;

CREATE TABLE tls206_person
/* p.person_id, p.person_ctry_code, p.doc_std_name_id, p.person_name, p.person_address, p.doc_std_name, p.doc_std_name_id_replenished, p.hrm_l1, p.hrm_l2, p.hrm_level, p.hrm_l2_id, p.sector, p.han_id, p.han_name, p.han_harmonized*/
	(
		PERSON_ID 			INT(11) NOT NULL,
		PERSON_CTRY_CODE 	VARCHAR(2) NOT NULL,
		DOC_STD_NAME_ID  	INT(11) NOT NULL,
		PERSON_NAME      	VARCHAR(500),
		PERSON_ADDRESS   	VARCHAR(500),
		DOC_STD_NAME				VARCHAR(100),
		DOC_STD_NAME_ID_REPLENISHED INT(11),
		HRM_L1						VARCHAR(400),
		HRM_L2						VARCHAR(400),
		HRM_LEVEL					INT (11),
		HRM_L2_ID					INT (11),
		SECTOR						VARCHAR(50),
		HAN_ID						INT (11),
		HAN_NAME					VARCHAR(500),
		HAN_HARMONIZED				TINYINT(4),
		PRIMARY KEY(PERSON_ID),
		FOREIGN KEY(DOC_STD_NAME_ID)  REFERENCES TLS208_DOC_STD_NMS(DOC_STD_NAME_ID)
	)
		ENGINE=INNODB CHARACTER SET utf8;
        
CREATE TABLE tls207_pers_appln
	(
		PERSON_ID 			int(11) NOT NULL,
		APPLN_ID  			int(11) NOT NULL,
		APPLT_SEQ_NR 		smallint(6) default NULL,
		INVT_SEQ_NR 		smallint(6) default NULL,
		PRIMARY KEY  (PERSON_ID, APPLN_ID, APPLT_SEQ_NR, INVT_SEQ_NR),
		FOREIGN KEY  (PERSON_ID)  	REFERENCES TLS206_PERSON(PERSON_ID),
		FOREIGN KEY  (APPLN_ID)  	REFERENCES TLS201_APPLN(APPLN_ID)
	)
		ENGINE=INNODB CHARACTER SET utf8;
	
CREATE TABLE tls209_appln_ipc
	(
		APPLN_ID  			int(11) NOT NULL,
		IPC_CLASS_SYMBOL   	VARCHAR(15) NOT NULL,
		IPC_CLASS_LEVEL    	CHAR(1),
		IPC_VERSION        	DATE,
		IPC_VALUE          	CHAR(1),
		IPC_POSITION       	CHAR(1),
		IPC_GENER_AUTH     	CHAR(2),
		IPC_SUBCLASS_SYMBOL CHAR(4),
		TECHN_FIELD_NR		TINYINT(4),
		PRIMARY KEY  (APPLN_ID, IPC_CLASS_SYMBOL),
		FOREIGN KEY  (APPLN_ID)  REFERENCES TLS201_APPLN (APPLN_ID)
	)
		ENGINE=INNODB CHARACTER SET utf8;
	
CREATE TABLE tls210_appln_n_cls
	(
		APPLN_ID  			int(11)  NOT NULL,
		NAT_CLASS_SYMBOL   	VARCHAR(15) NOT NULL,
		PRIMARY KEY  (APPLN_ID, NAT_CLASS_SYMBOL),
		FOREIGN KEY  (APPLN_ID)  REFERENCES TLS201_APPLN (APPLN_ID)
	)
		ENGINE=INNODB CHARACTER SET utf8;
CREATE TABLE tls211_pat_publn
	(
		PAT_PUBLN_ID 		int(11)  NOT NULL,
		PUBLN_AUTH          CHAR(2) NOT NULL,
		PUBLN_NR            VARCHAR(15) NOT NULL,
		PUBLN_KIND          CHAR(2),
		APPLN_ID 			int(11) NOT NULL,
		PUBLN_DATE          DATE,
		PUBLN_LG            CHAR(2),
		PUBLN_FIRST_GRANT   SMALLINT(6),
		PUBLN_CLAIMS       	smallint(6) NOT NULL,
		PRIMARY KEY (PAT_PUBLN_ID),
		FOREIGN KEY  (APPLN_ID)  REFERENCES TLS201_APPLN (APPLN_ID)
	)
		ENGINE=INNODB CHARACTER SET utf8;
	
CREATE TABLE tls214_npl_publn
	(
		NPL_PUBLN_ID 		int(11) NOT NULL, 
		NPL_BIBLIO          VARCHAR(3000),
		PRIMARY KEY  (NPL_PUBLN_ID)
	)
		ENGINE=INNODB CHARACTER SET utf8;
    
CREATE TABLE tls212_citation
	(
		PAT_PUBLN_ID 		int(11) NOT NULL,
		CITN_ID  			smallint(6) NOT NULL,
		CITED_PAT_PUBLN_ID 	int(11) default NULL, /*doc says "0"==null? */
		CITED_APPLN_ID 		int(11) NOT NULL,
		PAT_CITN_SEQ_NR  	smallint(6) default NULL, /*doc says "0"==null? */
		NPL_PUBLN_ID  		int(11) NOT NULL,
		NPL_CITN_SEQ_NR 	smallint(6) default NULL, /*doc says "0"==null? */
		CITN_ORIGIN 		VARCHAR(5),
		CITN_GENER_AUTH  	CHAR(2) NOT NULL,
		PRIMARY KEY  (PAT_PUBLN_ID, CITN_ID),
		FOREIGN KEY  (PAT_PUBLN_ID)  		REFERENCES TLS211_PAT_PUBLN(PAT_PUBLN_ID),
		FOREIGN KEY  (CITED_PAT_PUBLN_ID)  	REFERENCES TLS211_PAT_PUBLN(PAT_PUBLN_ID),
		FOREIGN KEY  (CITED_APPLN_ID)  		REFERENCES TLS201_APPLN(APPLN_ID),
		FOREIGN KEY  (NPL_PUBLN_ID)  		REFERENCES TLS214_NPL_PUBLN(NPL_PUBLN_ID)
	)
		ENGINE=INNODB CHARACTER SET utf8;

CREATE TABLE tls215_citn_categ
	(
		PAT_PUBLN_ID  		int(11) NOT NULL,
		CITN_ID 			smallint(6) NOT NULL,
		CITN_CATEG       	CHAR(1) NOT NULL,
		PRIMARY KEY  (PAT_PUBLN_ID, CITN_ID, CITN_CATEG),
		FOREIGN KEY  (PAT_PUBLN_ID, CITN_ID)  REFERENCES TLS212_CITATION(PAT_PUBLN_ID,CITN_ID)
	)
		ENGINE=INNODB CHARACTER SET utf8;
        
CREATE TABLE tls216_appln_contn
	(
		APPLN_ID  			int(11) NOT NULL,
		PARENT_APPLN_ID  	int(11) NOT NULL,
		CONTN_TYPE      	CHAR(3),
		PRIMARY KEY  (APPLN_ID, PARENT_APPLN_ID),
		FOREIGN KEY  (APPLN_ID)  REFERENCES TLS201_APPLN(APPLN_ID),
		FOREIGN KEY  (PARENT_APPLN_ID)  REFERENCES TLS201_APPLN(APPLN_ID)
	)
		ENGINE=INNODB CHARACTER SET utf8;
        
/*CREATE TABLE TLS217_APPLN_ECLA
	(
		APPLN_ID  			int(11) NOT NULL,
		EPO_CLASS_AUTH 		VARCHAR(2) NOT NULL,
		EPO_CLASS_SCHEME 		VARCHAR(4) NOT NULL,
		EPO_CLASS_SYMBOL 		VARCHAR(50) NOT NULL,
	)
*/

CREATE TABLE TLS218_DOCDB_FAM
	(
		APPLN_ID  			int(11) NOT NULL,
		DOCDB_FAMILY_ID   	int(11) NOT NULL,
		PRIMARY KEY  (APPLN_ID),
		FOREIGN KEY  (APPLN_ID)  REFERENCES  TLS201_APPLN(APPLN_ID)
	)
		ENGINE=INNODB CHARACTER SET utf8;
        
CREATE TABLE TLS219_INPADOC_FAM
	(
		APPLN_ID  			int(11) NOT NULL,
		INPADOC_FAMILY_ID   int(11) NOT NULL,
		PRIMARY KEY  (APPLN_ID),
		FOREIGN KEY  (APPLN_ID)  REFERENCES  TLS201_APPLN(APPLN_ID)
	)	
		ENGINE=INNODB CHARACTER SET utf8;
		
/*CREATE TABLE TLS221_INPADOC_PRS
	(
		APPLN_ID  			INT(11),
		PRS_EVENT_SEQ_NR  	SMALLINT(6),
		PRS_GAZETTE_DATE  	DATE,
		PRS_CODE  			VARCHAR(4),
		L501EP
		L502EP
		LEC_ID
		L503EP
		L504EP
		L505EP
		L506EP
		L507EP
		L508EP
		L509EP
		L510EP
		L511EP
		L512EP
		L513EP
		L515EP
		L516EP
		L517EP
		L518EP
		L519EP
		L520EP
		L522EP
		L523EP
		L524EP
		L525EP
		PRIMARY KEY  (APPLN_ID, PRS_EVENT_SEQ_NR),
		FOREIGN KEY  (APPLN_ID)	REFERENCES  TLS201_APPLN(APPLN_ID),
		FOREIGN KEY  (LEC_ID)	REFERENCES TLS802_LEGAL_EVENT_CODE(LEC_ID) 
	)	
		ENGINE=INNODB CHARACTER SET utf8;
*/

CREATE TABLE TLS222_APPLN_JP_CLASS
	(
		APPLN_ID  			int(11) NOT NULL,
		JP_CLASS_SCHEME 	VARCHAR(5) NOT NULL,
		JP_CLASS_SYMBOL 	VARCHAR(50) NOT NULL,
		PRIMARY KEY  (APPLN_ID, JP_CLASS_SCHEME, JP_CLASS_SYMBOL),
		FOREIGN KEY  (APPLN_ID)  REFERENCES  TLS201_APPLN(APPLN_ID)
	)	
		ENGINE=INNODB CHARACTER SET utf8;

CREATE TABLE TLS223_APPLN_DOCUS
	(
		APPLN_ID  			int(11) NOT NULL,
		docus_class_symbol 	VARCHAR(50) NOT NULL,
		PRIMARY KEY  (APPLN_ID, DOCUS_CLASS_SYMBOL),
		FOREIGN KEY  (APPLN_ID)  REFERENCES  TLS201_APPLN (APPLN_ID)
	)	
		ENGINE=INNODB CHARACTER SET utf8;	

CREATE TABLE TLS224_APPLN_CPC
	(
		APPLN_ID 			INT(11),
		CPC_CLASS_SYMBOL	VARCHAR(11),
		CPC_SCHEME 			VARCHAR(5),
		CPC_VERSION 		DATE,
		CPC_VALUE			CHAR(1), 
		CPC_POSITION 		CHAR(1),
		CPC_GENER_AUTH 		CHAR(2),
		CPC_MAINGROUP_SYMBOL CHAR(8),
		PRIMARY KEY  (APPLN_ID, CPC_CLASS_SYMBOL, CPC_SCHEME),
		FOREIGN KEY  (APPLN_ID)  REFERENCES  TLS201_APPLN (APPLN_ID)
	)	
		ENGINE=INNODB CHARACTER SET utf8;

CREATE TABLE TLS226_PERSON_ORIG
	(
		PERSON_ORIG_ID 		INT(11),
		PERSON_ID 			INT(11),
		SOURCE 				CHAR(5),
		SOURCE_VERSION 		VARCHAR(10),
		/*Name attributes*/
		NAME_FREEFORM 		VARCHAR(500),
		LAST_NAME 			VARCHAR(400),
		FIRST_NAME 			varchar(200),
		MIDDLE_NAME 		varchar(50),
		/*Address attributes*/
		ADDRESS_FREEFORM 	VARCHAR(1000),
		STREET 				VARCHAR(500),
		CITY 				VARCHAR(200),
		ZIP_CODE 			VARCHAR(30),
		STATE 				CHAR(2),
		PERSON_CTRY_CODE 	CHAR(2),
		RESIDENCE_CTRY_CODE CHAR(2),
		/*Other attributes*/	
		ROLE				VARCHAR(2),
		PRIMARY KEY  (PERSON_ORIG_ID),
		FOREIGN KEY  (PERSON_ID)  REFERENCES TLS206_PERSON(PERSON_ID)
	)
		ENGINE=INNODB CHARACTER SET utf8;
/*CREATE TABLE DOCDB_FAMILY_CITATION
	(
		CITED_DOCDB_FAMILY_ID 	INT(11) NOT NULL,
		CITING_DOCDB_FAMILY_ID	INT(11) NOT NULL,
		PRIMARY KEY  (CITED_DOCDB_FAMILY_ID, CITING_DOCDB_FAMILY_ID),
		FOREIGN KEY  (CITED_DOCDB_FAMILY_ID)  	REFERENCES TLS218_DOCDB_FAM(DOCDB_FAMILY_ID),
		FOREIGN KEY  (CITING_DOCDB_FAMILY_ID)  	REFERENCES TLS218_DOCDB_FAM(DOCDB_FAMILY_ID)
	)
		ENGINE=INNODB CHARACTER SET utf8;
*/