---------------------------------------------------------------------------------------------
-- Clustering
---------------------------------------------------------------------------------------------

--create table for results
if object_id('npl_publn_clusters') is not null drop table npl_publn_clusters
create table npl_publn_clusters
(
	cluster int,
	npl_publn_id int
)

/**
In the table 'publn_pairs' we store all the pairs generated by the matching rules.
*/

--all one both sides, nieuw
if object_id('tmp_publn_pairs2') is not null drop table tmp_publn_pairs2
select npl_publn_id1, npl_publn_id2
into tmp_publn_pairs2
from publn_pairs 
union
select npl_publn_id2, npl_publn_id1
from publn_pairs 

--select distinct publn's
if object_id('tmp_publns2') is not null drop table tmp_publns2
select distinct npl_publn_id = npl_publn_id1
into tmp_publns2
from tmp_publn_pairs2

--index publn's start at 0
if object_id('tmp_publns3') is not null drop table tmp_publns3
select pub_index = cast((row_number() over (order by npl_publn_id) - 1) as int), npl_publn_id
into tmp_publns3
from tmp_publns2

--index pairs 
if object_id('tmp_publn_pairs3') is not null drop table tmp_publn_pairs3
select pair_index = cast(row_number() over (order by b.pub_index, c.pub_index) - 1 as int), publn1_index = b.pub_index, publn2_index = c.pub_index
into tmp_publn_pairs3
from tmp_publn_pairs2 as a
join tmp_publns3 as b on a.npl_publn_id1 = b.npl_publn_id 
join tmp_publns3 as c on a.npl_publn_id2 = c.npl_publn_id

--determine min and max pair, nieuw
if object_id('tmp_publns4') is not null drop table tmp_publns4
select a.pub_index, a.npl_publn_id, b.min_pair_index, b.max_pair_index
into tmp_publns4
from tmp_publns3 as a
left join
(
	select pub_index = publn1_index, min_pair_index = min(pair_index), max_pair_index = max(pair_index)
	from tmp_publn_pairs3
	group by publn1_index
) as b on a.pub_index = b.pub_index


--insert into table (call stored procedure)
insert into npl_publn_clusters
exec patstat_sample.[dbo].[GetConnectedPublnSets]
-- or exec [dbo].[GetConnectedPublnSets]


--clean up
if object_id('tmp_publn_pairs2') is not null drop table tmp_publn_pairs2
if object_id('tmp_publns2') is not null drop table tmp_publns2
if object_id('tmp_publns3') is not null drop table tmp_publns3
if object_id('tmp_publn_pairs3') is not null drop table tmp_publn_pairs3
if object_id('tmp_publns4') is not null drop table tmp_publns4


